"""empty message

Revision ID: 1abd4d78cdfc
Revises: 433bf04caaac
Create Date: 2014-10-17 10:36:34.512000

"""

# revision identifiers, used by Alembic.
revision = '1abd4d78cdfc'
down_revision = '433bf04caaac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.drop_column('users', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('users', 'full_name')
    ### end Alembic commands ###
