"""empty message

Revision ID: 32744cd21b8b
Revises: 1abd4d78cdfc
Create Date: 2014-10-20 22:46:38.544000

"""

# revision identifiers, used by Alembic.
revision = '32744cd21b8b'
down_revision = '1abd4d78cdfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('verified_email', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_email')
    op.drop_column('users', 'profile_pic')
    ### end Alembic commands ###
