"""empty message

Revision ID: 3e10748dd8a9
Revises: None
Create Date: 2014-10-17 08:34:23.485000

"""

# revision identifiers, used by Alembic.
revision = '3e10748dd8a9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
