"""empty message

Revision ID: 4940a264383c
Revises: 5859599fc157
Create Date: 2014-11-14 10:52:18.297000

"""

# revision identifiers, used by Alembic.
revision = '4940a264383c'
down_revision = '5859599fc157'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
