"""empty message

Revision ID: 5859599fc157
Revises: 32744cd21b8b
Create Date: 2014-11-14 10:48:48.906000

"""

# revision identifiers, used by Alembic.
revision = '5859599fc157'
down_revision = '32744cd21b8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    ### end Alembic commands ###
